version: '3'

services:
    platformtracker_api:
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/platformtracker_api/node_modules
        command: npm run debug

    platformtracker_db:
        restart: always


volumes:
    node_modules: